FROM node:20-alpine

WORKDIR /app

COPY package*.json ./
COPY prisma ./prisma/

RUN npm install

COPY . .

# Generate Prisma Client
RUN npx prisma generate

EXPOSE 3000

# Start server
CMD ["npm", "run", "dev"] 
# In a real prod env, we would build and run 'node dist/server.js'
